### ISSUE TITLE
document how to update cached .inv files

### ISSUE THREAD

**Issue by ktdreyer** [ansible-community/sphinx_ansible_theme#22]
[`docs/conf.py`](https://github.com/ansible-community/sphinx_ansible_theme/blob/6898ec42f470552a2bb66dc6e08ab2a47b16fff6/docs/conf.py#L265-L267) says:

> Note:  Our strategy for intersphinx mappings is to have the upstream build location as the
> canonical source and then cached copies of the mapping stored locally in case someone is building
> when disconnected from the internet.  We then have a script to update the cached copies.

What script does that?

**Comment by ktdreyer** [comment]
(FYI the intersphinx mappings came up during the Fedora package review in [rhbz#1858503](https://bugzilla.redhat.com/show_bug.cgi?id=1858503))

**Comment by webknjaz** [comment]
I think this was just copied from ansible/ansible and most folks probably don't need this cache.

FWIW you should be able to download the intersphinx mappings using
```
$ python -m sphinx.ext.intersphinx https://docs.python.org/3/objects.inv
```

Also, @abadger wrote a script for this in the Core repo some time back https://github.com/ansible/ansible/pull/66646/files#diff-76be13d257cf5c18b30c66364445527fR1.

**Comment by webknjaz** [comment]
I'm pretty sure intersphinx is not used for the demo page https://sphinx-ansible-theme.readthedocs.io/en/latest/ (that's what the `docs/` folder contains). And also building this example is probably not very useful for Fedora RPMs so I'd maybe just drop that dir altogether from the package.

**Comment by webknjaz** [comment]
Let's see what @ssbarnea thinks since it was he who committed that config.

**Comment by ktdreyer** [comment]
Tangentially, I was also thinking that "`ansible_X_Y`" version list is yet another list of static version numbers that is going to go stale over time, and I wondered what the criteria is for adding/deleting versions from that list.

If we could delete the entire intersphinx configuration, that sounds great to me.

**Comment by abadger** [comment]
The fedora review should be fine (and indeed it was accepted).  I wrote the fallbacks to use a cached copy with things like building in Koji in mind. (So that intersphinx links could be built even in a disconnected environment like Koji)

I wouldn't think the theme itself would need intersphinx... But then again, i wouldn't think it needs a conf.py so I might not know what all the theme does.

If it does need intersphinx, a simple shell script using webknjaz's example is probably sufficient. The script i wrote tries to make it so the docs team can add new entries and the release team can simply run the script to update them without talking to each other in the common case.  Most other places probably don't even have a separate set of people managing the docs and the release...

**Comment by ssbarnea** [comment]
I dislike ``ansible_X_Y`` too as it is prone to produce outdated links. I would be more than happy to see a solution to avoid it.

**Comment by webknjaz** [comment]
@abadger that `conf.py` is not part of the theme but belongs to the sphinx setup for this demo preview https://sphinx-ansible-theme.readthedocs.io/ of the theme. It's rather `docs/` on how to use this thing.

Also, a lot of things were extracted as is, w/o checking whether they are necessary since it requires a bit more effort but we're getting there, just slowly.

**Comment by webknjaz** [comment]
@ktdreyer unless you want a preview example for how this theme looks, it should be safe to just remove `docs/` dir altogether (or not to build it for that matter).

**Comment by Chedi** [comment]
hi,

I'm the maintainer of the phython-phynx_ansible_theme package on fedora that @ktdreyer is refering to. Just wanted to butt in to say the network access in koji is not blocking the package building. In fact, the resulting docs/ folder is used in a sub package python-sphinx_ansible_theme-doc and whether or not you get access to the intersphinx the resulting files are the same and the demo is still working the same.

**Comment by webknjaz** [comment]
@Chedi yes, I know. Sphinx just emits warnings. But then, you can run it in nitpick mode and warnings will become errors. So it's better not to have any warnings and be strict about it.
I just want to reiterate that the intersphinx has been extracted from ansible/ansible, it's just a copy-paste and is not used anywhere at all, it only produces noise atm. And so it's reasonable to remove it. In fact, it must be removed as we approach refactoring `docs/conf.py`.

**Comment by webknjaz** [comment]
`intersphinx_mapping` has been removed from the demo site config.
